name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Comment PR with test results
        uses: actions/github-script@v6
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const testResult = '${{ job.status }}' === 'success' ? '✅ Tests passed' : '❌ Tests failed';
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: `## Test Results\n\n${testResult}\n\nSee details in the [Actions tab](https://github.com/${owner}/${repo}/actions/runs/${{ github.run_id }}).`
            });
